### ISSUE TITLE
[87页][倒数第四行]源码调试项目中没有ReactFiberFlags.js文件

### ISSUE THREAD

**Issue by waleiwalei** [BetaSu/react-design#11]
详细的勘误内容
"所有flags都在packages/react-reconciler/src/ReaactFiberFlags.js中定义"
项目代码中没有packages/react-reconciler目录,可以补充一下

<img width="547" alt="image" src="https://user-images.githubusercontent.com/13348384/211131535-257ab087-8fa1-4048-b191-4cab74d9ff0e.png">
xiang'mu

**Comment by BetaSu** [comment]
这里是指 所有flags都在React项目下的packages/react-reconciler/src/ReaactFiberFlags.js中定义。 
react18-demo下是用于调试的demo
