### ISSUE TITLE
[98][3.5编程] 配套示例好像无法运行

### ISSUE THREAD

**Issue by captain1023** [BetaSu/react-design#17]
详细的勘误内容
<img width="1404" alt="image" src="https://user-images.githubusercontent.com/30490036/220663266-b3637c65-ca52-440b-9ed1-9c86b8ddabb4.png">

**Comment by captain1023** [comment]
react选择18版本解决,卡颂老师要不要考虑在哪里给示例标注下使用包的版本,方便学者调试

**Comment by BetaSu** [comment]
好的，感谢反馈
