### ISSUE TITLE
[108][4.1.1] 子阶段的执行流程

### ISSUE THREAD

**Issue by captain1023** [BetaSu/react-design#18]
会完成**自下而上**的subtreeFalgs标记过程,那么commit阶段的三个子阶段会完成'自下而上'的subtreeFalgs消费过程.
如果按照书中理解,第二个应该是‘自上而下’的样子?

**Comment by BetaSu** [comment]
你可以思考下，如果commit阶段也是自上而下，那么删除节点时，父组件会先删除，子组件再删除
