### ISSUE TITLE
[221][15] enqueueUpdate应该放在判断是否命中eagerState优化策略之后

### ISSUE THREAD

**Issue by changxxuan** [BetaSu/react-design#20]
const alternate = fiber.alternate;
if (fiber.lanes === NoLanes &&  (alternate === null || alternate.lanes === NoLanes)) {
    // 省略代码
}
enqueueUpdate(fiber, queue, update, lane);

enqueueUpdate中会把lane合并到fiber.lanes和alternate.lanes，放在前面，就不会命中了吧

**Comment by BetaSu** [comment]
enqueueUpdate只是做 update链表的操作，不会操作lanes
