### ISSUE TITLE
[18][1] “与自变量建立对应关系的抽象层级”为条件对框架进行分类例子

### ISSUE THREAD

**Issue by Fhasghrge** [BetaSu/react-design#3]
这一块反复看了几遍，但是没能理解为什么React是应用级框架，而Vue是组件级框架？

会是Vue通过Proxy精准映射了自变量和组件的关系吗，而React是要全部diff一遍查找差异更新？

作者大大能举个例子解答疑惑吗？ 感谢

**Comment by BetaSu** [comment]
这里是作为勘误的，答疑请到 群里提问，thx～
就你的问题来说，vue的更新触发机制是建立在 状态与组件，即状态变化，组件更新。而React是建立在 状态与应用，即状态变化，应用完整更新。
