### ISSUE TITLE
[81页码][8行] 建议将“是否可中断”改为“是否应该中断”

### ISSUE THREAD

**Issue by jgchenu** [BetaSu/react-design#4]
shouldYield (是否可中断)
建议改为“是否应该中断”，看过源码的人应该知道，要表达这个状态应该要，并且是强制要被执行的，“是否可中断” 会被没看过源码的读者理解为可选执行

**Comment by BetaSu** [comment]
从语义上讲，`shouldYield`翻译为“是否应该中断”确实更贴切
