### ISSUE TITLE
[120页] Mutation阶段介绍

### ISSUE THREAD

**Issue by gumingWu** [BetaSu/react-design#6]
详细的勘误内容

4.4章节，Mutation阶段

在react18.2.0中，已经没有`commitMutationEffects_begin/complete`方法

直接在`commitMutationEffects`方法中执行`commitMutationEffectsOnFiber`方法

**Comment by BetaSu** [comment]
这不属于书内容的勘误。 如果想沟通版本变化的影响，可以在书对应的群里沟通
