### ISSUE TITLE
[223页码][22行] 将“这是因为App、Child并未进入render阶段”改为“这是因为Child并未进入render阶段” 

### ISSUE THREAD

**Issue by jgchenu** [BetaSu/react-design#7]
App肯定是进入render阶段了，不然不会打印出来`App render 1`,而是子组件child命中bailout没进入render阶段不会打印`child render`

**Comment by BetaSu** [comment]
文中原话为：
> 再观察“后续点击不会打印”，这是因为 App、Child 并未进入 render 阶段
既然后续不会打印，就不存在打印`App render 1`了，`App`也就不会进入`render`阶段

**Comment by jgchenu** [comment]
Get，那是我这边看错了，触发了egerState优化没毛病
